#!/usr/bin/env python3
"""Generate MicroBlaze chart header from editable text charts."""

from __future__ import annotations

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CHARTS = [
    ("Song0", "canon", ROOT / "charts" / "canon.mbchart"),
    ("Song1", "faded", ROOT / "charts" / "faded.mbchart"),
    ("Song2", "aphasia", ROOT / "charts" / "aphasia.mbchart"),
]
OUT = ROOT / "Mini_IO.sdk" / "SeriesIODacSaw" / "src" / "generated_charts.h"

LANES = {
    "L": "LANE_LEFT",
    "LEFT": "LANE_LEFT",
    "C": "LANE_MID",
    "M": "LANE_MID",
    "MID": "LANE_MID",
    "CENTER": "LANE_MID",
    "R": "LANE_RIGHT",
    "RIGHT": "LANE_RIGHT",
}


def beats_to_ms(beats: float, bpm: float) -> int:
    return int(round(beats * 60000.0 / bpm))


def parse_time_token(token: str, path: Path, line_no: int, meta: dict) -> int:
    raw = token.strip()
    upper = raw.upper()
    if upper.endswith("MS"):
        raw = raw[:-2]
    if upper.endswith("B"):
        try:
            beats = float(raw[:-1])
        except ValueError as exc:
            raise ValueError(f"{path}:{line_no}: invalid beat time '{token}'") from exc
        return int(meta["offset_ms"]) + beats_to_ms(beats, float(meta["bpm"]))
    if ":" in raw:
        fields = raw.split(":")
        if len(fields) != 2:
            raise ValueError(f"{path}:{line_no}: beat time must be bar:beat")
        try:
            bar = int(fields[0])
            beat = float(fields[1])
        except ValueError as exc:
            raise ValueError(f"{path}:{line_no}: invalid beat time '{token}'") from exc
        beats = bar * float(meta["beats_per_bar"]) + beat
        return int(meta["offset_ms"]) + beats_to_ms(beats, float(meta["bpm"]))
    try:
        return int(raw)
    except ValueError as exc:
        raise ValueError(f"{path}:{line_no}: invalid time '{token}'") from exc


def parse_duration_token(token: str, path: Path, line_no: int, meta: dict) -> int:
    raw = token.strip()
    upper = raw.upper()
    if upper.endswith("MS"):
        raw = raw[:-2]
    if upper.endswith("B"):
        try:
            beats = float(raw[:-1])
        except ValueError as exc:
            raise ValueError(f"{path}:{line_no}: invalid beat duration '{token}'") from exc
        return beats_to_ms(beats, float(meta["bpm"]))
    try:
        return int(raw)
    except ValueError as exc:
        raise ValueError(f"{path}:{line_no}: invalid duration '{token}'") from exc


def parse_chart(path: Path):
    notes = []
    meta = {
        "bpm": 120.0,
        "offset_ms": 0,
        "beats_per_bar": 4,
    }
    for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        clean = re.sub(r"#.*$", "", raw).strip()
        if not clean:
            continue
        if clean.startswith("@"):
            parts = clean.split()
            if len(parts) != 2:
                raise ValueError(f"{path}:{line_no}: directive must be '@name value'")
            name = parts[0][1:].lower()
            if name == "bpm":
                meta["bpm"] = float(parts[1])
            elif name == "offset_ms":
                meta["offset_ms"] = int(parts[1])
            elif name == "beats_per_bar":
                meta["beats_per_bar"] = int(parts[1])
            else:
                raise ValueError(f"{path}:{line_no}: unknown directive '@{name}'")
            continue
        parts = clean.split()
        if len(parts) not in (2, 4):
            raise ValueError(f"{path}:{line_no}: expected 'time_ms lane' or 'time_ms lane hold length_ms'")
        time_ms = parse_time_token(parts[0], path, line_no, meta)
        lane = LANES.get(parts[1].upper())
        if lane is None:
            raise ValueError(f"{path}:{line_no}: invalid lane '{parts[1]}'")
        hold = 0
        length_ms = 0
        if len(parts) == 4:
            if parts[2].lower() not in ("hold", "h"):
                raise ValueError(f"{path}:{line_no}: third field must be hold")
            hold = 1
            length_ms = parse_duration_token(parts[3], path, line_no, meta)
            if length_ms <= 0:
                raise ValueError(f"{path}:{line_no}: hold length must be positive")
        if not 0 <= time_ms <= 65535:
            raise ValueError(f"{path}:{line_no}: time_ms must fit u16")
        if not 0 <= length_ms <= 65535:
            raise ValueError(f"{path}:{line_no}: length_ms must fit u16")
        notes.append((time_ms, lane, hold, length_ms))
    notes.sort(key=lambda item: item[0])
    return notes


def main() -> None:
    lines = [
        "/* Generated by scripts/generate_mb_charts.py.",
        " * Edit the mbchart files under charts, then rebuild the SDK ELF.",
        " */",
        "#ifndef GENERATED_CHARTS_H",
        "#define GENERATED_CHARTS_H",
        "",
    ]
    for symbol, label, path in CHARTS:
        notes = parse_chart(path)
        lines.append(f"static const Note {symbol}[] = {{")
        for time_ms, lane, hold, length_ms in notes:
            lines.append(f"    {{ {time_ms:5d}, {lane:10s}, {hold:d}, {length_ms:5d} }},")
        lines.append("};")
        lines.append(f"#define {symbol.upper()}_LEN ((u8)(sizeof({symbol}) / sizeof({symbol}[0])))")
        lines.append("")
        print(f"{label}: {len(notes)} notes")
    lines.append("#endif")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
